name: Settlements
version: 1.0
description: Settlements
main: broseidon4.Settlements
commands:
    settlements:
        description: asdf
        permission: command.settlements
permissions:
  command.settlements:
    description: settlements.
    default: op
